### ISSUE TITLE
error: unknown option '-reate'

### ISSUE THREAD

**Issue by PigCharid** [IErcOrg/ierc-miner-js#4]
pigcharid@192 ierc-miner-js % yarn cli wallet -create
yarn run v1.22.19
warning ../../../package.json: No license field
$ ts-node src/cli.ts wallet -create
error: unknown option '-reate'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by S-helios** [comment]
use `yarn cli wallet --create` or `yarn cli wallet -c`
![1700738583481](https://github.com/IErcOrg/ierc-miner-js/assets/58353477/47f8ffe3-b99b-44f6-baf4-a9992a8bca91)

**Comment by SheriffWoody** [comment]
yarn cli wallet --create

**Comment by magrisya** [comment]
try
`$ yarn cli wallet --create`

**Comment by solobat** [comment]
`$ yarn cli wallet --c`
